version: '3.8'
services:
  movies:
    image: joshikunal178/paytmmoviesss:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
    volumes:
      - "movies"
  train:
    image: joshikunal178/paytmtrainsss:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
    volumes:
      - "train"
  dth:
    image: joshikunal178/paytmdthsss:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
    volumes:
      - "dth"
  recharge:
    image: joshikunal178/paytmrechargesss:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
    volumes:
      - "recharge"
